import ClsBound
import AltAlg
import CutAlg

/-!
# Saturated state sets and their spans

The finiteness proof for the reachable-state set of the v3 engine is organised
around the predicate `Sat U P`: `P` is a finite set of regexes that the engine
cannot escape from.  Besides the obvious closure under `deriv` and `derivW`,
saturation asks for the *structural* closures the derivative recursion needs:

* the members of a union (`altToList`) and of an intersection (`cutToList`)
  of a state are states — this is what lets `altL`/`cutL` be applied to states
  without leaving `P`;
* the class of every `sym` state is bounded by `U`, and *every* class bounded
  by `U` gives a `sym` state — since `altL`/`cutL` merge `sym` members by
  folding `Cls.union`/`Cls.inter`, and `ClsBound.lean` bounds those folds;
* the body of a complement state is a state (`not_` peels one);
* the suffixes of the concatenation chain of a state are states, and so is the
  chain obtained by deriving its head factor (`headD_mem`, `headW_mem`) — the
  two operations a derivative of a concatenation performs.

Nothing here needs the ACI canonicity layer: the arguments are structural,
which is what makes them applicable to *arbitrary* (possibly non-canonical)
input terms.

`AltSpan A` (`CutSpan A`) is the set of smart unions (intersections) of lists
of atoms taken from `A`; the main theorems of this file (`sat_altPool`,
`sat_cutPool`) say that such a span is saturated as soon as the atom set is.
-/

namespace Redgrep

open Smart

/-! ### Atom sets -/

/-- The structural conditions an *atom set* must satisfy: it is finite, holds
the three constants, is closed under union- and intersection-members, and its
`sym` states are exactly the classes bounded by `U`. -/
structure AtomSet (U : Finset Char) (A : Set RE) : Prop where
  finite : A.Finite
  eps_mem : (RE.eps) ∈ A
  nil_mem : (RE.nil) ∈ A
  top_mem : top ∈ A
  sym_mem : ∀ cl, ClsOK U cl → sym cl ∈ A
  sym_cls : ∀ cl, (RE.sym cl) ∈ A → ClsOK U cl
  alt_atom : ∀ x ∈ A, ∀ y ∈ altToList x, y ∈ A
  cut_atom : ∀ x ∈ A, ∀ y ∈ cutToList x, y ∈ A

/-- A **saturated** set of states: an atom set which the engine cannot leave. -/
structure Sat (U : Finset Char) (P : Set RE) : Prop extends AtomSet U P where
  not_body : ∀ y : RE, (RE.not y) ∈ P → y ∈ P
  deriv_mem : ∀ x ∈ P, ∀ c, deriv c x ∈ P
  derivW_mem : ∀ x ∈ P, ∀ w, derivW w x ∈ P
  suffix_mem : ∀ x ∈ P, ∀ i, seqOfList ((seqToList x).drop i) ∈ P
  headD_mem : ∀ x ∈ P, ∀ h rest, seqToList x = h :: rest → ∀ c,
      seqOfList (seqToList (deriv c h) ++ rest) ∈ P
  headW_mem : ∀ x ∈ P, ∀ h rest, seqToList x = h :: rest → ∀ w,
      seqOfList (seqToList (derivW w h) ++ rest) ∈ P

/-- Every state reachable by reading a word stays inside a saturated set. -/
theorem Sat.derivs_mem {U : Finset Char} {P : Set RE} (hP : Sat U P) {r : RE} (hr : r ∈ P)
    (u : List Char) : u.foldl (fun t c => deriv c t) r ∈ P := by
  induction u generalizing r with
  | nil => exact hr
  | cons c u ih => exact ih (hP.deriv_mem r hr c)

/-! ### Flattened member lists -/

/-- A list of union members is unchanged by flattening. -/
theorem altFlat_eq_self {M : List RE} (h : ∀ x ∈ M, x ≠ .nil ∧ NotAlt x) : altFlat M = M := by
  induction M with
  | nil => rfl
  | cons x xs ih =>
    obtain ⟨hn, ha⟩ := h x (by simp)
    rw [altFlat_cons, altToList_eq_singleton hn ha, ih fun y hy => h y (by simp [hy])]
    rfl

/-- A list of intersection members is unchanged by flattening. -/
theorem cutFlat_eq_self {M : List RE} (h : ∀ x ∈ M, x ≠ top ∧ NotCut x) : cutFlat M = M := by
  induction M with
  | nil => rfl
  | cons x xs ih =>
    obtain ⟨hn, ha⟩ := h x (by simp)
    rw [cutFlat_cons, cutToList_eq_singleton hn ha, ih fun y hy => h y (by simp [hy])]
    rfl

theorem altFlat_shape (L : List RE) : ∀ x ∈ altFlat L, x ≠ .nil ∧ NotAlt x := by
  intro x hx
  obtain ⟨r, -, hxr⟩ := mem_altFlat.mp hx
  exact ⟨(mem_altToList_shape x hxr).2, (mem_altToList_shape x hxr).1⟩

theorem cutFlat_shape (L : List RE) : ∀ x ∈ cutFlat L, x ≠ top ∧ NotCut x := by
  intro x hx
  obtain ⟨r, -, hxr⟩ := mem_cutFlat.mp hx
  exact ⟨(mem_cutToList_shape x hxr).2, (mem_cutToList_shape x hxr).1⟩

theorem altL_altFlat (L : List RE) : altL L = altL (altFlat L) :=
  altL_congr_mem (by rw [altFlat_eq_self (altFlat_shape L)]; exact fun _ => Iff.rfl)

theorem cutL_cutFlat (L : List RE) : cutL L = cutL (cutFlat L) :=
  cutL_congr_mem (by rw [cutFlat_eq_self (cutFlat_shape L)]; exact fun _ => Iff.rfl)

/-! ### Spans -/

/-- All smart unions of atoms taken from `A`. -/
def AltSpan (A : Set RE) : Set RE := {x | ∃ L : List RE, (∀ y ∈ L, y ∈ A) ∧ x = altL L}

/-- All smart intersections of atoms taken from `A`. -/
def CutSpan (A : Set RE) : Set RE := {x | ∃ L : List RE, (∀ y ∈ L, y ∈ A) ∧ x = cutL L}

/-- The state pool generated by an atom set through smart unions. -/
def AltPool (A : Set RE) : Set RE := A ∪ AltSpan A

/-- The state pool generated by an atom set through smart intersections. -/
def CutPool (A : Set RE) : Set RE := A ∪ CutSpan A

theorem altSpan_finite {A : Set RE} (hA : A.Finite) : (AltSpan A).Finite := by
  classical
  refine Set.Finite.subset
    (Set.Finite.image (fun T : Finset RE => altL T.toList)
      (hA.toFinset.powerset.finite_toSet)) ?_
  rintro x ⟨L, hL, rfl⟩
  refine ⟨L.toFinset, ?_, ?_⟩
  · simp only [Finset.coe_powerset, Set.mem_preimage, Set.mem_powerset_iff, Finset.coe_subset]
    intro y hy
    exact hA.mem_toFinset.mpr (hL y (List.mem_toFinset.mp hy))
  · exact (altL_mem_congr (by intro y; simp)).symm

theorem cutSpan_finite {A : Set RE} (hA : A.Finite) : (CutSpan A).Finite := by
  classical
  refine Set.Finite.subset
    (Set.Finite.image (fun T : Finset RE => cutL T.toList)
      (hA.toFinset.powerset.finite_toSet)) ?_
  rintro x ⟨L, hL, rfl⟩
  refine ⟨L.toFinset, ?_, ?_⟩
  · simp only [Finset.coe_powerset, Set.mem_preimage, Set.mem_powerset_iff, Finset.coe_subset]
    intro y hy
    exact hA.mem_toFinset.mpr (hL y (List.mem_toFinset.mp hy))
  · exact (cutL_mem_congr (by intro y; simp)).symm


/-! ### The merged `sym` member -/

theorem mem_altMerged_eq {L : List RE} {z : RE} (hz : z ∈ altMerged L) :
    ∃ c cs, symClasses L = c :: cs ∧ z = sym (cs.foldl Cls.union c) := by
  unfold altMerged at hz
  split at hz
  · simp at hz
  · rename_i c cs hsc
    split at hz
    · simp at hz
    · rename_i s hs
      rw [List.mem_singleton] at hz
      exact ⟨c, cs, hsc, hz⟩

theorem mem_cutMerged_eq {L : List RE} {z : RE} (hz : z ∈ cutMerged L) :
    ∃ c cs, symClasses L = c :: cs ∧ z = sym (cs.foldl Cls.inter c) := by
  unfold cutMerged at hz
  split at hz
  · simp at hz
  · rename_i c cs hsc
    rw [List.mem_singleton] at hz
    exact ⟨c, cs, hsc, hz⟩

theorem altOfList_shape (M : List RE) :
    Redgrep.altOfList M = .nil ∨ (∃ p q, Redgrep.altOfList M = .alt p q) ∨
      Redgrep.altOfList M ∈ M := by
  match M with
  | [] => exact Or.inl rfl
  | [m] => exact Or.inr (Or.inr (by simp [Redgrep.altOfList]))
  | m :: n :: M' =>
    exact Or.inr (Or.inl ⟨m, Redgrep.altOfList (n :: M'), by
      rw [Smart.altOfList_cons, if_neg (by simp)]⟩)

theorem cutOfList_shape (M : List RE) :
    Redgrep.cutOfList M = top ∨ (∃ p q, Redgrep.cutOfList M = .cut p q) ∨
      Redgrep.cutOfList M ∈ M := by
  match M with
  | [] => exact Or.inl rfl
  | [m] => exact Or.inr (Or.inr (by simp [Redgrep.cutOfList]))
  | m :: n :: M' =>
    exact Or.inr (Or.inl ⟨m, Redgrep.cutOfList (n :: M'), by
      rw [Smart.cutOfList_cons, if_neg (by simp)]⟩)

/-! ### The members of a span element are atoms -/

theorem altL_mem_atoms {U : Finset Char} {A : Set RE} (hA : AtomSet U A) {L : List RE}
    (hL : ∀ y ∈ L, y ∈ A) : ∀ z ∈ altToList (altL L), z ∈ A := by
  have hflat : ∀ y ∈ altFlat L, y ∈ A := by
    intro y hy
    obtain ⟨r, hr, hyr⟩ := mem_altFlat.mp hy
    exact hA.alt_atom r (hL r hr) y hyr
  by_cases htop : top ∈ altFlat L
  · rw [altL_eq', if_pos htop, altToList_top]
    intro z hz
    rw [List.mem_singleton] at hz
    subst hz
    exact hA.top_mem
  · rw [altToList_altL htop]
    intro z hz
    rw [mem_sortDedup, List.mem_append] at hz
    rcases hz with hz | hz
    · obtain ⟨c, cs, hsc, rfl⟩ := mem_altMerged_eq hz
      refine hA.sym_mem _ (clsOK_foldl_union ?_ ?_)
      · refine hA.sym_cls c (hflat _ ?_)
        have : (RE.sym c) ∈ (altFlat L).filter isSym := mem_symClasses.mp (by rw [hsc]; simp)
        exact (List.mem_filter.mp this).1
      · intro d hd
        refine hA.sym_cls d (hflat _ ?_)
        have : (RE.sym d) ∈ (altFlat L).filter isSym := mem_symClasses.mp (by rw [hsc]; simp [hd])
        exact (List.mem_filter.mp this).1
    · exact hflat z (List.mem_filter.mp hz).1

theorem cutL_mem_atoms {U : Finset Char} {A : Set RE} (hA : AtomSet U A) {L : List RE}
    (hL : ∀ y ∈ L, y ∈ A) : ∀ z ∈ cutToList (cutL L), z ∈ A := by
  have hflat : ∀ y ∈ cutFlat L, y ∈ A := by
    intro y hy
    obtain ⟨r, hr, hyr⟩ := mem_cutFlat.mp hy
    exact hA.cut_atom r (hL r hr) y hyr
  by_cases hnil : (RE.nil) ∈ cutFlat L
  · rw [cutL_eq', if_pos hnil]
    intro z hz
    rw [Smart.cutToList_nil, List.mem_singleton] at hz
    subst hz
    exact hA.nil_mem
  by_cases hm : (RE.nil) ∈ cutMerged ((cutFlat L).filter isSym)
  · rw [cutL_eq', if_neg hnil, cutBody_eq', if_pos hm]
    intro z hz
    rw [Smart.cutToList_nil, List.mem_singleton] at hz
    subst hz
    exact hA.nil_mem
  · rw [cutToList_cutL hnil hm]
    intro z hz
    rw [mem_sortDedup, List.mem_append] at hz
    rcases hz with hz | hz
    · obtain ⟨c, cs, hsc, rfl⟩ := mem_cutMerged_eq hz
      refine hA.sym_mem _ (clsOK_foldl_inter ?_ ?_)
      · refine hA.sym_cls c (hflat _ ?_)
        have : (RE.sym c) ∈ (cutFlat L).filter isSym := mem_symClasses.mp (by rw [hsc]; simp)
        exact (List.mem_filter.mp this).1
      · intro d hd
        refine hA.sym_cls d (hflat _ ?_)
        have : (RE.sym d) ∈ (cutFlat L).filter isSym := mem_symClasses.mp (by rw [hsc]; simp [hd])
        exact (List.mem_filter.mp this).1
    · exact hflat z (List.mem_filter.mp hz).1

/-! ### Spans absorb smart unions of their members -/

theorem altL_mem_altSpan {U : Finset Char} {A : Set RE} (hA : AtomSet U A) {L : List RE}
    (hL : ∀ y ∈ L, y ∈ AltPool A) : altL L ∈ AltSpan A := by
  refine ⟨altFlat L, ?_, altL_altFlat L⟩
  intro y hy
  obtain ⟨r, hr, hyr⟩ := mem_altFlat.mp hy
  rcases hL r hr with h | ⟨M, hM, rfl⟩
  · exact hA.alt_atom r h y hyr
  · exact altL_mem_atoms hA hM y hyr

theorem cutL_mem_cutSpan {U : Finset Char} {A : Set RE} (hA : AtomSet U A) {L : List RE}
    (hL : ∀ y ∈ L, y ∈ CutPool A) : cutL L ∈ CutSpan A := by
  refine ⟨cutFlat L, ?_, cutL_cutFlat L⟩
  intro y hy
  obtain ⟨r, hr, hyr⟩ := mem_cutFlat.mp hy
  rcases hL r hr with h | ⟨M, hM, rfl⟩
  · exact hA.cut_atom r h y hyr
  · exact cutL_mem_atoms hA hM y hyr

/-! ### The shape of a span element -/

theorem altL_shape {U : Finset Char} {A : Set RE} (hA : AtomSet U A) {L : List RE}
    (hL : ∀ y ∈ L, y ∈ A) :
    altL L = top ∨ altL L = .nil ∨ (∃ p q, altL L = .alt p q) ∨ altL L ∈ A := by
  by_cases htop : top ∈ altFlat L
  · exact Or.inl (by rw [altL_eq', if_pos htop])
  have hmem := altL_mem_atoms hA hL
  have h2 : altL L = Redgrep.altOfList (altToList (altL L)) := by
    rw [altToList_altL htop, altL_eq', if_neg htop]
  rcases altOfList_shape (altToList (altL L)) with h | ⟨p, q, hpq⟩ | h
  · exact Or.inr (Or.inl (by rw [h2, h]))
  · exact Or.inr (Or.inr (Or.inl ⟨p, q, by rw [h2, hpq]⟩))
  · exact Or.inr (Or.inr (Or.inr (by rw [h2]; exact hmem _ h)))

theorem cutL_shape {U : Finset Char} {A : Set RE} (hA : AtomSet U A) {L : List RE}
    (hL : ∀ y ∈ L, y ∈ A) :
    cutL L = top ∨ cutL L = .nil ∨ (∃ p q, cutL L = .cut p q) ∨ cutL L ∈ A := by
  by_cases hnil : (RE.nil) ∈ cutFlat L
  · exact Or.inr (Or.inl (by rw [cutL_eq', if_pos hnil]))
  by_cases hm : (RE.nil) ∈ cutMerged ((cutFlat L).filter isSym)
  · exact Or.inr (Or.inl (by rw [cutL_eq', if_neg hnil, cutBody_eq', if_pos hm]))
  have hmem := cutL_mem_atoms hA hL
  have h2 : cutL L = Redgrep.cutOfList (cutToList (cutL L)) := by
    rw [cutToList_cutL hnil hm, cutL_eq', if_neg hnil, cutBody_eq', if_neg hm]
  rcases cutOfList_shape (cutToList (cutL L)) with h | ⟨p, q, hpq⟩ | h
  · exact Or.inl (by rw [h2, h])
  · exact Or.inr (Or.inr (Or.inl ⟨p, q, by rw [h2, hpq]⟩))
  · exact Or.inr (Or.inr (Or.inr (by rw [h2]; exact hmem _ h)))

/-! ### Derivative-like maps on a span -/

/-- The abstract shape of `deriv c` and `derivW w` used by the span lemmas:
a homomorphism for the raw `alt` node fixing `nil` and `top`. -/
theorem altSpan_map {U : Finset Char} {A : Set RE} (hA : AtomSet U A) (F : RE → RE)
    (hFalt : ∀ p q, F (.alt p q) = alt2 (F p) (F q))
    (hFnil : F .nil = .nil) (hFtop : F top = top)
    (hFA : ∀ x ∈ A, F x ∈ AltPool A) :
    ∀ x ∈ AltSpan A, F x ∈ AltPool A := by
  have key : ∀ M : List RE, (∀ m ∈ M, m ∈ A) → F (Redgrep.altOfList M) ∈ AltPool A := by
    intro M
    induction M with
    | nil =>
      intro _
      rw [show Redgrep.altOfList ([] : List RE) = .nil from rfl, hFnil]
      exact Or.inl hA.nil_mem
    | cons m M' ih =>
      intro hM
      rw [Smart.altOfList_cons]
      split
      · exact hFA m (hM m (by simp))
      · rw [hFalt, alt2]
        exact Or.inr (altL_mem_altSpan hA (by
          intro y hy
          rcases List.mem_cons.mp hy with rfl | hy
          · exact hFA m (hM m (by simp))
          · rcases List.mem_cons.mp hy with rfl | hy
            · exact ih fun z hz => hM z (by simp [hz])
            · simp at hy))
  rintro x ⟨L, hL, rfl⟩
  by_cases htop : top ∈ altFlat L
  · rw [altL_eq', if_pos htop, hFtop]
    exact Or.inl hA.top_mem
  · rw [altL_eq', if_neg htop]
    refine key _ ?_
    intro m hm
    refine altL_mem_atoms hA hL m ?_
    rw [altToList_altL htop]
    exact hm

theorem cutSpan_map {U : Finset Char} {A : Set RE} (hA : AtomSet U A) (F : RE → RE)
    (hFcut : ∀ p q, F (.cut p q) = cut2 (F p) (F q))
    (hFnil : F .nil = .nil) (hFtop : F top = top)
    (hFA : ∀ x ∈ A, F x ∈ CutPool A) :
    ∀ x ∈ CutSpan A, F x ∈ CutPool A := by
  have key : ∀ M : List RE, (∀ m ∈ M, m ∈ A) → F (Redgrep.cutOfList M) ∈ CutPool A := by
    intro M
    induction M with
    | nil =>
      intro _
      rw [show Redgrep.cutOfList ([] : List RE) = top from rfl, hFtop]
      exact Or.inl hA.top_mem
    | cons m M' ih =>
      intro hM
      rw [Smart.cutOfList_cons]
      split
      · exact hFA m (hM m (by simp))
      · rw [hFcut, cut2]
        exact Or.inr (cutL_mem_cutSpan hA (by
          intro y hy
          rcases List.mem_cons.mp hy with rfl | hy
          · exact hFA m (hM m (by simp))
          · rcases List.mem_cons.mp hy with rfl | hy
            · exact ih fun z hz => hM z (by simp [hz])
            · simp at hy))
  rintro x ⟨L, hL, rfl⟩
  by_cases hnil : (RE.nil) ∈ cutFlat L
  · rw [cutL_eq', if_pos hnil, hFnil]
    exact Or.inl hA.nil_mem
  by_cases hm : (RE.nil) ∈ cutMerged ((cutFlat L).filter isSym)
  · rw [cutL_eq', if_neg hnil, cutBody_eq', if_pos hm, hFnil]
    exact Or.inl hA.nil_mem
  · rw [cutL_eq', if_neg hnil, cutBody_eq', if_neg hm]
    refine key _ ?_
    intro m hmm
    refine cutL_mem_atoms hA hL m ?_
    rw [cutToList_cutL hnil hm]
    exact hmm

end Redgrep
